<?php
session_start(); require_once 'config/db.php'; require_once 'config/auth.php'; require_security_login();
$error='';$success='';
$id=security_user_id();
if($_SERVER['REQUEST_METHOD']==='POST'){
 $current=$_POST['current_password']??'';$new=$_POST['new_password']??'';$confirm=$_POST['confirm_password']??'';
 $stmt=$conn->prepare("SELECT password FROM security_users WHERE id=?");$stmt->bind_param("i",$id);$stmt->execute();$row=$stmt->get_result()->fetch_assoc();$stmt->close();
 if(!$row||!password_verify($current,$row['password'])) $error='Current password is incorrect.';
 elseif(strlen($new)<8||$new!==$confirm)$error='New password must be at least 8 characters and match confirmation.';
 else{$hash=password_hash($new,PASSWORD_DEFAULT);$up=$conn->prepare("UPDATE security_users SET password=?,updated_at=CURRENT_TIMESTAMP WHERE id=?");$up->bind_param("si",$hash,$id);$up->execute();$up->close();$success='Password changed successfully.';security_audit($conn,'Changed account password');}
}
$stmt=$conn->prepare("SELECT full_name,username,email,phone FROM security_users WHERE id=?");$stmt->bind_param("i",$id);$stmt->execute();$me=$stmt->get_result()->fetch_assoc();$stmt->close();
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Security Profile | ParkSmart</title><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.0/css/all.min.css"><style>
*{box-sizing:border-box}body{margin:0;background:#f5f7fb;font-family:Arial,sans-serif;color:#172033}.wrap{max-width:950px;margin:50px auto;padding:0 20px}.top{background:linear-gradient(135deg,#07162e,#1e3a8a);color:#fff;border-radius:22px;padding:25px 30px;display:flex;justify-content:space-between;align-items:center;gap:15px}.top h1{margin:0}.top a{color:#fff;text-decoration:none}.grid{display:grid;grid-template-columns:1fr 1fr;gap:22px;margin-top:22px}.card{background:#fff;border:1px solid #e2e8f0;border-radius:20px;padding:25px;box-shadow:0 10px 30px rgba(0,0,0,.05)}.card h2{margin-top:0;color:#0a192f}.info{display:grid;gap:12px}.info div{padding:13px;background:#f8fafc;border-radius:12px}.info b{display:block;font-size:11px;color:#64748b;text-transform:uppercase;margin-bottom:4px}.group{margin-bottom:15px}.group label{display:block;font-size:12px;font-weight:800;margin-bottom:7px}.group input{width:100%;padding:13px;border:1px solid #dce3ec;border-radius:11px}.btn{width:100%;padding:14px;border:0;border-radius:11px;background:#ff6b00;color:#fff;font-weight:800}.alert{padding:12px;border-radius:10px;margin-bottom:15px;font-weight:700}.ok{background:#ecfdf5;color:#047857}.err{background:#fff1f2;color:#be123c}@media(max-width:700px){.grid{grid-template-columns:1fr}.top{align-items:flex-start;flex-direction:column}}
</style><?php include __DIR__ . "/includes/pwa.php"; ?></head><body><div class="wrap"><div class="top"><div><h1><i class="fa-solid fa-user-shield"></i> Security Profile</h1><div><?=htmlspecialchars($me['full_name'])?> · @<?=htmlspecialchars($me['username'])?></div></div><a href="index.php"><i class="fa-solid fa-arrow-left"></i> Back to Parking</a></div><div class="grid"><div class="card"><h2>Account Details</h2><div class="info"><div><b>Full Name</b><?=htmlspecialchars($me['full_name'])?></div><div><b>Username</b><?=htmlspecialchars($me['username'])?></div><div><b>Email</b><?=htmlspecialchars($me['email'])?></div><div><b>Phone</b><?=htmlspecialchars($me['phone']?:'Not provided')?></div></div></div><div class="card"><h2>Change Password</h2><?php if($success):?><div class="alert ok"><?=htmlspecialchars($success)?></div><?php endif;?><?php if($error):?><div class="alert err"><?=htmlspecialchars($error)?></div><?php endif;?><form method="post"><div class="group"><label>Current Password</label><input type="password" name="current_password" required></div><div class="group"><label>New Password</label><input type="password" name="new_password" minlength="8" required></div><div class="group"><label>Confirm New Password</label><input type="password" name="confirm_password" minlength="8" required></div><button class="btn">Change Password</button></form></div></div></div></body></html>
